name: PR Check

on:
  pull_request:
    branches: [main] # Asegúrate de especificar las ramas adecuadas

jobs:
  build-test-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run tests
        run: mvn clean test

      - name: Build and run the application
        run: mvn spring-boot:run &

      - name: Wait for application to start
        run: sleep 30

      - name: Run API endpoint tests
        run: |

          curl --fail http://localhost:8000/api/users || exit 1

      - name: Cleanup
        if: always()
        run: |

          SPRING_BOOT_PID=$(pgrep -f 'spring-boot')
          if [ ! -z "$SPRING_BOOT_PID" ]; then
            echo "Stopping Spring Boot application..."
            kill $SPRING_BOOT_PID
          fi
